
# ignore migration files

AllCops:
  DisabledByDefault: false
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
  NewCops: enable
  
Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  Max: 40

Layout/LineLength:
  Max: 400

Metrics/AbcSize:
  Max: 40

Metrics/ModuleLength:
  Max: 150